spring:
  cache:
    redis:
      time-to-live: PT10000S
      use-key-prefix: true
      key-prefix: payment_cache_

  redis:
    host: 127.0.0.1
    port: 6379
    password: ybq
    database: 2
    jedis:
      pool:
        max-active: 600 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 300 #连接池中的最大空闲连接

logging:
  level:
    root: info
  file: yanglog.txt

my:
  name: yyy
